### ISSUE TITLE
Can the model itself does not download the tokenizers or base model ?

### ISSUE THREAD

**Issue by ZohaibRamzan** [Vinayaks117/AWS-SageMaker-Examples#1]
I want to confirm whether the models or tokenizers need to be downloaded first and need to add to the model directory. Or during runtime, it can download itself.

**Comment by vinayak-shanawad** [comment]
Yes, if we want to use pre-trained models then it can be downloaded, saved in model_dir path then tokenizer and models will be loaded while starting the server.

**Comment by ZohaibRamzan** [comment]
> Yes, if we want to use pre-trained models then it can be downloaded, saved in model_dir path then tokenizer and models will be loaded while starting the server.

You mean I can't download the model or tokenizer from huggingface website? I need to store the required models before hand and then load using model_dir?

**Comment by vinayak-shanawad** [comment]
I mean you can download both of them from huggingface with in `model_fn` function, save it in `model_dir` path.
