### ISSUE TITLE
I'm getting {"detail":"Not Found"} when I predict the model

### ISSUE THREAD

**Issue by skuchipu** [Vinayaks117/AWS-SageMaker-Examples#2]
I'm using Kubeflow 1.8 with KServe 0.12 and used your example for testing and receiving below error while predicting the model 

{"detail":"Not Found"}

I'm using pathTemplate in inferenceservice-config and used "/serving/models/{{ .Name }}" 

**using below curl to get the prediction**
curl -v -H "http://xx.xx.xx.xx/serving/models/kserve-custom-model" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d @./input.json   [http://xx.xx.xx.xx:80/serving/models/kserve-custom-model/v1/models/bert-sentiment:predict](http://xx.xx.xx.xx/serving/models/kserve-custom-model/v1/models/bert-sentiment:predict)

Is there anything i'm missing

**Comment by vinayak-shanawad** [comment]
Hi @skuchipu 

Can you list the inference service using this command `kubectl get inferenceservices`?

Did you install Istio and port-forwarded while testing the model?

Looks like your curl command is not right. Here is the right command.

`curl -v -H "Host: kserve-custom-model.default.example.com" http://localhost:8080/v1/models/bert-sentiment:predict  -d @./input.json`

**Comment by skuchipu** [comment]
Hi @vinayak-shanawad  , Its working for me , I was able to get it working with the URL config and made changes to my inference config , now am able to predict my model . thank you for your example .
